version: '3.3'

services:
  flask:
    build: ./flask
    restart: always
    container_name: flask
    ports:
        - "5000:5000"
    volumes:
      - ./flask/src:/app
    networks:
      - frontend
      - backend
    secrets:
      - jwt_secret_key
      - mysql_root_password
      - cert
      - privkey
    depends_on:
        - mysql
  mysql:
    build: ./mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    networks:
      - backend
    secrets:
      - mysql_root_password

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
secrets:
  mysql_root_password:
    file: ./mysql/secrets/mysql_root_password.txt
  jwt_secret_key:
    file: ./flask/secrets/jwt_secret_key.txt
  cert:
    file: /etc/letsencrypt/live/tonych.me/cert.pem
  privkey:
    file: /etc/letsencrypt/live/tonych.me/privkey.pem
